### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by djbelieny** [timqian/weekly-report#1]
/usr/local/lib/node_modules/weekly-report/index.js:45
  for(let i = 0; i < dirArr.length; i++) {
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Additional Info:

Node: v4.3.2
Npm: 3.8.9
MacOS Sierra / 10.12.2 (16C67)
iTerm

**Comment by timqian** [comment]
Fixed, Try to install it again.
